/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WeathernowCard {
        "error": boolean;
        "humidity": string;
        "isActiveByDefault": boolean;
        "lastUpdate": string;
        "loading": boolean;
        "location": string;
        "pressure": string;
        "temperature": string;
        "temperatureColor": 'orange' | 'blue' | 'red';
    }
    interface WeathernowCardBody {
        "error": boolean;
        "loading": boolean;
        "temperature": string;
        "temperatureColor": 'red' | 'orange' | 'blue';
    }
    interface WeathernowCardFooter {
        "humidity": string;
        "isActive": boolean;
        "lastUpdate": string;
        "pressure": string;
    }
    interface WeathernowCardHeader {
        "location": string;
    }
    interface WeathernowTopbar {
    }
}
declare global {
    interface HTMLWeathernowCardElement extends Components.WeathernowCard, HTMLStencilElement {
    }
    var HTMLWeathernowCardElement: {
        prototype: HTMLWeathernowCardElement;
        new (): HTMLWeathernowCardElement;
    };
    interface HTMLWeathernowCardBodyElement extends Components.WeathernowCardBody, HTMLStencilElement {
    }
    var HTMLWeathernowCardBodyElement: {
        prototype: HTMLWeathernowCardBodyElement;
        new (): HTMLWeathernowCardBodyElement;
    };
    interface HTMLWeathernowCardFooterElement extends Components.WeathernowCardFooter, HTMLStencilElement {
    }
    var HTMLWeathernowCardFooterElement: {
        prototype: HTMLWeathernowCardFooterElement;
        new (): HTMLWeathernowCardFooterElement;
    };
    interface HTMLWeathernowCardHeaderElement extends Components.WeathernowCardHeader, HTMLStencilElement {
    }
    var HTMLWeathernowCardHeaderElement: {
        prototype: HTMLWeathernowCardHeaderElement;
        new (): HTMLWeathernowCardHeaderElement;
    };
    interface HTMLWeathernowTopbarElement extends Components.WeathernowTopbar, HTMLStencilElement {
    }
    var HTMLWeathernowTopbarElement: {
        prototype: HTMLWeathernowTopbarElement;
        new (): HTMLWeathernowTopbarElement;
    };
    interface HTMLElementTagNameMap {
        "weathernow-card": HTMLWeathernowCardElement;
        "weathernow-card-body": HTMLWeathernowCardBodyElement;
        "weathernow-card-footer": HTMLWeathernowCardFooterElement;
        "weathernow-card-header": HTMLWeathernowCardHeaderElement;
        "weathernow-topbar": HTMLWeathernowTopbarElement;
    }
}
declare namespace LocalJSX {
    interface WeathernowCard {
        "error"?: boolean;
        "humidity"?: string;
        "isActiveByDefault"?: boolean;
        "lastUpdate"?: string;
        "loading"?: boolean;
        "location"?: string;
        "pressure"?: string;
        "temperature"?: string;
        "temperatureColor"?: 'orange' | 'blue' | 'red';
    }
    interface WeathernowCardBody {
        "error"?: boolean;
        "loading"?: boolean;
        "temperature"?: string;
        "temperatureColor"?: 'red' | 'orange' | 'blue';
    }
    interface WeathernowCardFooter {
        "humidity"?: string;
        "isActive"?: boolean;
        "lastUpdate"?: string;
        "pressure"?: string;
    }
    interface WeathernowCardHeader {
        "location"?: string;
    }
    interface WeathernowTopbar {
    }
    interface IntrinsicElements {
        "weathernow-card": WeathernowCard;
        "weathernow-card-body": WeathernowCardBody;
        "weathernow-card-footer": WeathernowCardFooter;
        "weathernow-card-header": WeathernowCardHeader;
        "weathernow-topbar": WeathernowTopbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "weathernow-card": LocalJSX.WeathernowCard & JSXBase.HTMLAttributes<HTMLWeathernowCardElement>;
            "weathernow-card-body": LocalJSX.WeathernowCardBody & JSXBase.HTMLAttributes<HTMLWeathernowCardBodyElement>;
            "weathernow-card-footer": LocalJSX.WeathernowCardFooter & JSXBase.HTMLAttributes<HTMLWeathernowCardFooterElement>;
            "weathernow-card-header": LocalJSX.WeathernowCardHeader & JSXBase.HTMLAttributes<HTMLWeathernowCardHeaderElement>;
            "weathernow-topbar": LocalJSX.WeathernowTopbar & JSXBase.HTMLAttributes<HTMLWeathernowTopbarElement>;
        }
    }
}
